// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'orange': string;
  'row': string;
  'wide': string;
}
export const cssExports: CssExports;
export default cssExports;
