// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'display': string;
  'value': string;
}
export const cssExports: CssExports;
export default cssExports;
